# Чеклист добавленных символов
# - [х] 1234567890
# - [х] !"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~
# - [х]  \t\n
# - [х] ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮЁ
# - [х] йцукенгшщзхъфывапролджэячсмитьбюё


[modifiers]
	lshift = 'lpinky'
	lctr = 'lpinky'
	lalt = 'lthumb'
	rshift = 'rpinky'
	rctr = 'rpinky'
	ralt = 'rthumb'
	switchlayout = ['lpinky', 'lthumb']

[lthumb]
keys = [
	{letter=' ', modifiers=[]},
]

[lpinky]
keys = [
	{letter='ф', modifiers=[], score=0},
	{letter='й', modifiers=[], score=1},
	{letter='я', modifiers=[], score=1},
	{letter='ё', modifiers=[], score=3},
	{letter='Ф', modifiers=['lshift'], score=0},
	{letter='Й', modifiers=['lshift'], score=1},
	{letter='Я', modifiers=['lshift'], score=1},
	{letter='Ё', modifiers=['lshift'], score=3},
	{letter="\t", modifiers=[], score=2},
	{letter='`', modifiers=['switchlayout'], score=3},
	{letter='~', modifiers=['switchlayout', 'lshift'], score=3},
]

[lring]
keys = [
	{letter='ц', modifiers=[], score=1},
	{letter='ы', modifiers=[], score=0}
	{letter='ч', modifiers=[], score=1},
	{letter='Ц', modifiers=['lshift'], score=1},
	{letter='Ы', modifiers=['lshift'], score=0},
	{letter='Ч', modifiers=['lshift'], score=1},
	{letter='1', modifiers=[], score=3},
	{letter='2', modifiers=[], score=2},
	{letter='!', modifiers=['lshift'], score=3},
	{letter='@', modifiers=['lshift'], score=2},
	{letter='"', modifiers=['switchlayout', 'lshift'], score=2},
]

[lmiddle]
keys = [
	{letter='у', modifiers=[], score=1},
	{letter='в', modifiers=[], score=0},
	{letter='с', modifiers=[], score=1},
	{letter='У', modifiers=['lshift'], score=1},
	{letter='В', modifiers=['lshift'], score=0},
	{letter='С', modifiers=['lshift'], score=1},
	{letter='3', modifiers=[], score=2},
	{letter='4', modifiers=[], score=2},
	{letter='#', modifiers=['switchlayout', 'lshift'], score=2},
	{letter='$', modifiers=['switchlayout', 'lshift'], score=2},
	{letter=';', modifiers=['lshift'], score=2},
]

[lindex]
keys = [
	{letter='к', modifiers=[], score=1},
	{letter='а', modifiers=[], score=0},
	{letter='м', modifiers=[], score=1},
	{letter='е', modifiers=[], score=2},
	{letter='п', modifiers=[], score=1},
	{letter='и', modifiers=[], score=2},
	{letter='К', modifiers=['lshift'], score=1},
	{letter='А', modifiers=['lshift'], score=0},
	{letter='М', modifiers=['lshift'], score=1},
	{letter='Е', modifiers=['lshift'], score=2},
	{letter='П', modifiers=['lshift'], score=1},
	{letter='И', modifiers=['lshift'], score=2},
	{letter='5', modifiers=[], score=2},
	{letter='6', modifiers=[], score=3},
	{letter='%', modifiers=['lshift'], score=2},
	{letter='^', modifiers=['switchlayout', 'lshift'], score=3},
	{letter=':', modifiers=['lshift'], score=3},
]

[rindex]
keys = [
	{letter='н', modifiers=[], score=2},
	{letter='р', modifiers=[], score=1},
	{letter='т', modifiers=[], score=2},
	{letter='г', modifiers=[], score=1},
	{letter='о', modifiers=[], score=0},
	{letter='ь', modifiers=[], score=1},
	{letter='Н', modifiers=['lshift'], score=2},
	{letter='Р', modifiers=['lshift'], score=1},
	{letter='Т', modifiers=['lshift'], score=2},
	{letter='Г', modifiers=['lshift'], score=1},
	{letter='О', modifiers=['lshift'], score=0},
	{letter='Ь', modifiers=['lshift'], score=1},
	{letter='7', modifiers=[], score=2},
	{letter='&', modifiers=['switchlayout', 'lshift'], score=2},
	{letter='?', modifiers=['lshift'], score=2},
]

[rmiddle]
keys = [
	{letter='ш', modifiers=[], score=1},
	{letter='л', modifiers=[], score=0},
	{letter='б', modifiers=[], score=1},
	{letter='Ш', modifiers=['lshift'], score=1},
	{letter='Л', modifiers=['lshift'], score=0},
	{letter='Б', modifiers=['lshift'], score=1},
	{letter='8', modifiers=[], score=2},
	{letter='9', modifiers=[], score=2},
	{letter='*', modifiers=['lshift'], score=2},
	{letter='(', modifiers=['lshift'], score=2},
	{letter='<', modifiers=['switchlayout', 'lshift'], score=1},
]

[rring]
keys = [
	{letter='щ', modifiers=[], score=1},
	{letter='д', modifiers=[], score=0},
	{letter='ю', modifiers=[], score=1},
	{letter='Щ', modifiers=['lshift'], score=1},
	{letter='Д', modifiers=['lshift'], score=0},
	{letter='Ю', modifiers=['lshift'], score=1},
	{letter='0', modifiers=[], score=2},
	{letter=')', modifiers=['lshift'], score=2},
	{letter='>', modifiers=['switchlayout', 'lshift'], score=1},
]

[rpinky]
keys = [
	{letter='з', modifiers=[], score=1},
	{letter='ж', modifiers=[], score=0},
	{letter='э', modifiers=[], score=1},
	{letter='х', modifiers=[], score=2},
	{letter='ъ', modifiers=[], score=3},
	{letter='З', modifiers=['lshift'], score=1},
	{letter='Ж', modifiers=['lshift'], score=0},
	{letter='Э', modifiers=['lshift'], score=1},
	{letter='Х', modifiers=['lshift'], score=2},
	{letter='Ъ', modifiers=['lshift'], score=3},
	{letter="\n", modifiers=[], score=2},
	{letter='=', modifiers=[], score=4},
	{letter='+', modifiers=['lshift'], score=4},
	{letter='-', modifiers=[], score=3},
	{letter='_', modifiers=['lshift'], score=3},
	{letter=',', modifiers=['lshift'], score=1},
	{letter='.', modifiers=[], score=1},
	{letter="'", modifiers=['switchlayout'], score=1},
	{letter='\', modifiers=[], score=4},
	{letter='|', modifiers=['switchlayout', 'lshift'], score=4},
	{letter='/', modifiers=['lshift'], score=1},
	{letter='[', modifiers=['switchlayout'], score=2},
	{letter=']', modifiers=['switchlayout'], score=2},
	{letter='{', modifiers=['switchlayout', 'lshift'], score=2},
	{letter='}', modifiers=['switchlayout', 'lshift'], score=2},
]
