[lpinky]
keys = [
	'ф',
	'й',
	'я',
	'ё'
]

[lring]
keys = [
	'ц',
	'ы',
	'ч'
]

[lmiddle]
keys = [
	'у',
	'в',
	'с'
]

[lindex]
keys = [
	'к',
	'а',
	'м',
	'е',
	'п',
	'и'
]

[rindex]
keys = [
	'н',
	'р',
	'т',
	'г',
	'о',
	'ь'
]

[rmiddle]
keys = [
	'ш',
	'л',
	'б'
]

[rring]
keys = [
	'щ',
	'д',
	'ю'
]

[rpinky]
keys = [
	'з',
	'ж',
	'э',
	'х',
	'ъ'
]